import { Play, BookOpen, Award, Code } from "lucide-react";

export const resourcesData = {
  html: {
    title: "HTML",
    description: "The standard markup language for creating web pages.",
    category: "Frontend",
    difficulty: "Beginner",
    resources: [
      {
        title: "HTML Full Course - Build a Website Tutorial",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=pQN-pnXPaVg",
        description: "Learn HTML from scratch and build a website.",
        duration: "2 hours",
        rating: 4.8,
        icon: Play,
      },
      {
        title: "MDN Web Docs: HTML",
        type: "Documentation",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
        description: "Comprehensive HTML documentation and guides.",
        duration: "Self-paced",
        rating: 4.9,
        icon: BookOpen,
      },
    ],
  },
  css: {
    title: "CSS",
    description: "Style sheet language for designing web pages.",
    category: "Frontend",
    difficulty: "Beginner",
    resources: [
      {
        title: "CSS Crash Course For Beginners",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=yfoY53QXEnI",
        description: "Learn CSS basics and styling techniques.",
        duration: "1.5 hours",
        rating: 4.7,
        icon: Play,
      },
      {
        title: "MDN Web Docs: CSS",
        type: "Documentation",
        url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
        description: "Comprehensive CSS documentation and guides.",
        duration: "Self-paced",
        rating: 4.9,
        icon: BookOpen,
      },
    ],
  },
  apis: {
    title: "APIs",
    description: "Application Programming Interfaces for connecting software components.",
    category: "Backend",
    difficulty: "Intermediate",
    resources: [
      {
        title: "RESTful API Design - Full Course",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=SLwpqD8n3d0",
        description: "Learn how to design and build RESTful APIs.",
        duration: "2 hours",
        rating: 4.7,
        icon: Play,
      },
      {
        title: "Postman API Fundamentals Student Expert Course",
        type: "Online Course",
        url: "https://www.postman.com/student-expert/intro/overview/",
        description: "Learn API fundamentals and testing with Postman.",
        duration: "Self-paced",
        rating: 4.8,
        icon: Award,
      },
    ],
  },
  aws: {
    title: "AWS",
    description: "Amazon Web Services - Cloud computing platform.",
    category: "Cloud",
    difficulty: "Intermediate",
    resources: [
      {
        title: "AWS Certified Cloud Practitioner Course",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=3hLmDS179YE",
        description: "AWS Cloud Practitioner certification course.",
        duration: "10 hours",
        rating: 4.8,
        icon: Play,
      },
      {
        title: "AWS Training and Certification",
        type: "Official Training",
        url: "https://aws.amazon.com/training/",
        description: "Official AWS training courses and certifications.",
        duration: "Various",
        rating: 4.8,
        icon: BookOpen,
      },
    ],
  },
  scalability: {
    title: "Scalability",
    description: "Designing systems that handle growth efficiently.",
    category: "System Design",
    difficulty: "Advanced",
    resources: [
      {
        title: "System Design Basics - Scalability",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=vvhC0FaFzTo",
        description: "Learn the basics of scalable system design.",
        duration: "1 hour",
        rating: 4.7,
        icon: Play,
      },
      {
        title: "Scalability Best Practices",
        type: "Article",
        url: "https://aws.amazon.com/architecture/scalability-best-practices/",
        description: "Best practices for building scalable systems.",
        duration: "Self-paced",
        rating: 4.8,
        icon: BookOpen,
      },
    ],
  },
  cybersecurity: {
    title: "Cybersecurity",
    description: "Protect systems, networks, and data from digital attacks",
    category: "Security",
    difficulty: "Intermediate",
    resources: [
      {
        title: "Cybrary Free Cybersecurity Courses",
        type: "Online Platform",
        url: "https://www.cybrary.it/",
        description: "Free cybersecurity training and certification prep",
        duration: "Various",
        rating: 4.7,
        icon: Award,
      },
      {
        title: "FreeCodeCamp Information Security",
        type: "Certification Course",
        url: "https://www.freecodecamp.org/learn/information-security/",
        description: "Information security certification with projects",
        duration: "300 hours",
        rating: 4.8,
        icon: Code,
      },
      {
        title: "CISA Cybersecurity Training",
        type: "Government Resource",
        url: "https://www.cisa.gov/cybersecurity-training-exercises",
        description: "Official cybersecurity training from CISA",
        duration: "Various",
        rating: 4.6,
        icon: BookOpen,
      },
      {
        title: "TryHackMe Free Labs",
        type: "Hands-on Labs",
        url: "https://tryhackme.com/",
        description: "Interactive cybersecurity challenges and labs",
        duration: "Self-paced",
        rating: 4.9,
        icon: Play,
      },
    ],
  },
  // ... (copy all other resourceData keys from your resource page here)
  excel: {
    title: "Excel",
    description: "Spreadsheet software for data analysis, visualization, and automation.",
    category: "Productivity",
    difficulty: "Beginner",
    resources: [
      {
        title: "Excel for Beginners - Full Course",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=Vl0H-qTclOg",
        description: "Learn the basics of Microsoft Excel, including formulas, charts, and data entry.",
        duration: "2 hours",
        rating: 4.8,
        icon: Play,
      },
      {
        title: "Excel Functions and Formulas",
        type: "Article",
        url: "https://support.microsoft.com/en-us/excel",
        description: "Official Microsoft documentation for Excel functions and formulas.",
        duration: "Self-paced",
        rating: 4.7,
        icon: BookOpen,
      },
      {
        title: "Excel Practice Exercises",
        type: "Hands-on Practice",
        url: "https://excel-practice-online.com/",
        description: "Practice Excel skills with interactive exercises.",
        duration: "Self-paced",
        rating: 4.6,
        icon: Award,
      },
    ],
  },

  // --- Newly added skills ---
  react: {
    title: "React",
    description: "Build modern user interfaces with the React library.",
    category: "Frontend",
    difficulty: "Intermediate",
    resources: [
      {
        title: "React Official Tutorial",
        type: "Documentation",
        url: "https://react.dev/learn",
        description: "Official React learning resources.",
        duration: "Self-paced",
        rating: 4.8,
        icon: BookOpen,
      },
      {
        title: "React Crash Course",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=w7ejDZ8SWv8",
        description: "FreeCodeCamp React crash course.",
        duration: "2 hours",
        rating: 4.7,
        icon: Play,
      },
    ],
  },
  python: {
    title: "Python",
    description: "Versatile programming language for web, data science, and AI.",
    category: "Programming",
    difficulty: "Beginner",
    resources: [
      {
        title: "Python for Beginners",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=rfscVS0vtbw",
        description: "Learn Python basics in this crash course.",
        duration: "4 hours",
        rating: 4.8,
        icon: Play,
      },
      {
        title: "Official Python Docs",
        type: "Documentation",
        url: "https://docs.python.org/3/tutorial/",
        description: "Official Python documentation and tutorials.",
        duration: "Self-paced",
        rating: 4.7,
        icon: BookOpen,
      },
    ],
  },
  machinelearning: {
    title: "Machine Learning",
    description: "Build intelligent systems that learn from data.",
    category: "AI/ML",
    difficulty: "Advanced",
    resources: [
      {
        title: "Machine Learning Crash Course",
        type: "Online Course",
        url: "https://developers.google.com/machine-learning/crash-course",
        description: "Google's free ML crash course.",
        duration: "15 hours",
        rating: 4.8,
        icon: Award,
      },
      {
        title: "Intro to Machine Learning",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=Gv9_4yMHFhI",
        description: "Introductory ML video course.",
        duration: "1.5 hours",
        rating: 4.7,
        icon: Play,
      },
    ],
  },
  docker: {
    title: "Docker",
    description: "Containerize applications for scalable deployment.",
    category: "DevOps",
    difficulty: "Intermediate",
    resources: [
      {
        title: "Docker for Beginners",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=3c-iBn73dDE",
        description: "Docker crash course for beginners.",
        duration: "2 hours",
        rating: 4.8,
        icon: Play,
      },
      {
        title: "Docker Official Docs",
        type: "Documentation",
        url: "https://docs.docker.com/get-started/",
        description: "Official Docker getting started guide.",
        duration: "Self-paced",
        rating: 4.7,
        icon: BookOpen,
      },
    ],
  },
  typescript: {
    title: "TypeScript",
    description: "Strongly typed programming for scalable JavaScript apps.",
    category: "Programming",
    difficulty: "Intermediate",
    resources: [
      {
        title: "TypeScript for Beginners",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=30LWjhZzg50",
        description: "TypeScript crash course for beginners.",
        duration: "2 hours",
        rating: 4.7,
        icon: Play,
      },
      {
        title: "TypeScript Handbook",
        type: "Documentation",
        url: "https://www.typescriptlang.org/docs/handbook/intro.html",
        description: "Official TypeScript documentation.",
        duration: "Self-paced",
        rating: 4.8,
        icon: BookOpen,
      },
    ],
  },
  sql: {
    title: "SQL",
    description: "Query and manage relational databases.",
    category: "Database",
    difficulty: "Beginner",
    resources: [
      {
        title: "SQL Tutorial - Full Database Course",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=HXV3zeQKqGY",
        description: "Comprehensive SQL course for beginners.",
        duration: "4 hours",
        rating: 4.8,
        icon: Play,
      },
      {
        title: "SQLBolt Interactive Lessons",
        type: "Interactive Tutorial",
        url: "https://sqlbolt.com/",
        description: "Learn SQL with interactive lessons.",
        duration: "Self-paced",
        rating: 4.7,
        icon: Award,
      },
    ],
  },
  kubernetes: {
    title: "Kubernetes",
    description: "Orchestrate containers at scale.",
    category: "DevOps",
    difficulty: "Advanced",
    resources: [
      {
        title: "Kubernetes Crash Course",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=d6WC5n9G_sM",
        description: "Kubernetes crash course for beginners.",
        duration: "2 hours",
        rating: 4.7,
        icon: Play,
      },
      {
        title: "Kubernetes Official Docs",
        type: "Documentation",
        url: "https://kubernetes.io/docs/tutorials/",
        description: "Official Kubernetes tutorials.",
        duration: "Self-paced",
        rating: 4.8,
        icon: BookOpen,
      },
    ],
  },
  flutter: {
    title: "Flutter",
    description: "Build beautiful native apps for mobile, web, and desktop.",
    category: "Mobile Development",
    difficulty: "Intermediate",
    resources: [
      {
        title: "Flutter Crash Course",
        type: "Video Course",
        url: "https://www.youtube.com/watch?v=VPvVD8t02U8",
        description: "Flutter crash course for beginners.",
        duration: "3 hours",
        rating: 4.8,
        icon: Play,
      },
      {
        title: "Flutter Official Docs",
        type: "Documentation",
        url: "https://docs.flutter.dev/get-started/install",
        description: "Official Flutter getting started guide.",
        duration: "Self-paced",
        rating: 4.7,
        icon: BookOpen,
      },
    ],
  },
};
